In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [7]:
# load the dataset
df = pd.read_csv('Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [8]:
# preprocess the dataset
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
# encode categorical variables
label_encoder_gender = LabelEncoder()
df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [11]:
# onehot encode the 'Geography' column
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder_geo = OneHotEncoder(sparse=False)
geo_encoded = one_hot_encoder_geo.fit_transform(df[['Geography']])
geo_encoded

d:\enviroments\envs\tf\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [12]:
one_hot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [13]:
# drop unnecessary columns
geo_encoded_df = pd.DataFrame(geo_encoded, columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [14]:
# combine onehot encoded columns with the original dataframe
df = pd.concat([df.drop(['Geography'], axis=1), geo_encoded_df], axis=1)
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [15]:
# save the encoders and the scaler to pkl
with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)
    
with open('one_hot_encoder_geo.pkl', 'wb') as f:
    pickle.dump(one_hot_encoder_geo, f)

In [16]:
# divide the dataset into features and target variable
X = df.drop(['Exited'], axis=1)
y = df['Exited']

# split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [18]:
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

### ANN Implementation ###

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

import datetime

In [20]:
# build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid') # binary classification
    ]    
)

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2,945
Trainable params: 2,945
Non-trainable params: 0
_________________________________________________________________

In [23]:
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
tf.keras.losses.BinaryCrossentropy()

In [24]:
# compile the model
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [25]:
# setup tensorboard
log_dir = "logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [26]:
# set up early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [27]:
# train the model
history = model.fit(
    X_train, y_train, 
    epochs=100, 
    batch_size=32, 
    callbacks=[tensorboard_callback, early_stopping_callback]
)

Epoch 1/100
246/250 [============================>.] - ETA: 0s - loss: 0.3953 - accuracy: 0.8369WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 3s 3ms/step - loss: 0.3949 - accuracy: 0.8372
Epoch 2/100
236/250 [===========================>..] - ETA: 0s - loss: 0.3578 - accuracy: 0.8563WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3568 - accuracy: 0.8558
Epoch 3/100
230/250 [==========================>...] - ETA: 0s - loss: 0.3500 - accuracy: 0.8557WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3496 - accuracy: 0.8558
Epoch 4/100
248/250 [============================>.] - ETA: 0s - loss: 0.3451 - accuracy: 0.8557WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3451 - accuracy: 0.8556
Epoch 5/100
233/250 [==========================>...] - ETA: 0s - loss: 0.3452 - accuracy: 0.8588WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3426 - accuracy: 0.8601
Epoch 6/100
246/250 [============================>.] - ETA: 0s - loss: 0.3391 - accuracy: 0.8601WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3398 - accuracy: 0.8597
Epoch 7/100
236/250 [===========================>..] - ETA: 0s - loss: 0.3404 - accuracy: 0.8584WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3388 - accuracy: 0.8594
Epoch 8/100
231/250 [==========================>...] - ETA: 0s - loss: 0.3373 - accuracy: 0.8638WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3363 - accuracy: 0.8629
Epoch 9/100
240/250 [===========================>..] - ETA: 0s - loss: 0.3356 - accuracy: 0.8609WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3326 - accuracy: 0.8624
Epoch 10/100
243/250 [============================>.] - ETA: 0s - loss: 0.3271 - accuracy: 0.8632WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 3ms/step - loss: 0.3290 - accuracy: 0.8626
Epoch 11/100
247/250 [============================>.] - ETA: 0s - loss: 0.3271 - accuracy: 0.8642WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 3ms/step - loss: 0.3271 - accuracy: 0.8644
Epoch 12/100
235/250 [===========================>..] - ETA: 0s - loss: 0.3232 - accuracy: 0.8666WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 3ms/step - loss: 0.3248 - accuracy: 0.8658
Epoch 13/100
250/250 [==============================] - ETA: 0s - loss: 0.3251 - accuracy: 0.8659WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 3ms/step - loss: 0.3251 - accuracy: 0.8659
Epoch 14/100
240/250 [===========================>..] - ETA: 0s - loss: 0.3233 - accuracy: 0.8652WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3200 - accuracy: 0.8673
Epoch 15/100
242/250 [============================>.] - ETA: 0s - loss: 0.3223 - accuracy: 0.8688WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3231 - accuracy: 0.8681
Epoch 16/100
245/250 [============================>.] - ETA: 0s - loss: 0.3197 - accuracy: 0.8682WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3195 - accuracy: 0.8687
Epoch 17/100
229/250 [==========================>...] - ETA: 0s - loss: 0.3183 - accuracy: 0.8687WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3157 - accuracy: 0.8710
Epoch 18/100
230/250 [==========================>...] - ETA: 0s - loss: 0.3145 - accuracy: 0.8671WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3137 - accuracy: 0.8675
Epoch 19/100
239/250 [===========================>..] - ETA: 0s - loss: 0.3112 - accuracy: 0.8726WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3116 - accuracy: 0.8721
Epoch 20/100
238/250 [===========================>..] - ETA: 0s - loss: 0.3115 - accuracy: 0.8680WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3112 - accuracy: 0.8687
Epoch 21/100
229/250 [==========================>...] - ETA: 0s - loss: 0.3066 - accuracy: 0.8694WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 3ms/step - loss: 0.3078 - accuracy: 0.8684
Epoch 22/100
233/250 [==========================>...] - ETA: 0s - loss: 0.3051 - accuracy: 0.8745WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3062 - accuracy: 0.8740
Epoch 23/100
238/250 [===========================>..] - ETA: 0s - loss: 0.3002 - accuracy: 0.8726WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.3007 - accuracy: 0.8731
Epoch 24/100
233/250 [==========================>...] - ETA: 0s - loss: 0.2934 - accuracy: 0.8735WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 3ms/step - loss: 0.2991 - accuracy: 0.8720
Epoch 25/100
244/250 [============================>.] - ETA: 0s - loss: 0.2945 - accuracy: 0.8781WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 3ms/step - loss: 0.2942 - accuracy: 0.8785
Epoch 26/100
242/250 [============================>.] - ETA: 0s - loss: 0.2913 - accuracy: 0.8780WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2933 - accuracy: 0.8767
Epoch 27/100
247/250 [============================>.] - ETA: 0s - loss: 0.2931 - accuracy: 0.8758WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2932 - accuracy: 0.8759
Epoch 28/100
248/250 [============================>.] - ETA: 0s - loss: 0.2880 - accuracy: 0.8807WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2904 - accuracy: 0.8799
Epoch 29/100
245/250 [============================>.] - ETA: 0s - loss: 0.2871 - accuracy: 0.8791WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2863 - accuracy: 0.8799
Epoch 30/100
239/250 [===========================>..] - ETA: 0s - loss: 0.2866 - accuracy: 0.8800WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2852 - accuracy: 0.8810
Epoch 31/100
234/250 [===========================>..] - ETA: 0s - loss: 0.2856 - accuracy: 0.8802WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2863 - accuracy: 0.8795
Epoch 32/100
241/250 [===========================>..] - ETA: 0s - loss: 0.2798 - accuracy: 0.8815WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2803 - accuracy: 0.8816
Epoch 33/100
240/250 [===========================>..] - ETA: 0s - loss: 0.2797 - accuracy: 0.8786WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2817 - accuracy: 0.8773
Epoch 34/100
228/250 [==========================>...] - ETA: 0s - loss: 0.2710 - accuracy: 0.8842WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2737 - accuracy: 0.8827
Epoch 35/100
244/250 [============================>.] - ETA: 0s - loss: 0.2758 - accuracy: 0.8824WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2774 - accuracy: 0.8817
Epoch 36/100
240/250 [===========================>..] - ETA: 0s - loss: 0.2693 - accuracy: 0.8852WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2723 - accuracy: 0.8840
Epoch 37/100
249/250 [============================>.] - ETA: 0s - loss: 0.2722 - accuracy: 0.8840WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2727 - accuracy: 0.8836
Epoch 38/100
231/250 [==========================>...] - ETA: 0s - loss: 0.2725 - accuracy: 0.8820WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2730 - accuracy: 0.8821
Epoch 39/100
250/250 [==============================] - ETA: 0s - loss: 0.2669 - accuracy: 0.8845WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 3ms/step - loss: 0.2669 - accuracy: 0.8845
Epoch 40/100
242/250 [============================>.] - ETA: 0s - loss: 0.2644 - accuracy: 0.8870WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2650 - accuracy: 0.8867
Epoch 41/100
249/250 [============================>.] - ETA: 0s - loss: 0.2694 - accuracy: 0.8823WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2693 - accuracy: 0.8824
Epoch 42/100
231/250 [==========================>...] - ETA: 0s - loss: 0.2596 - accuracy: 0.8841WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2614 - accuracy: 0.8840
Epoch 43/100
245/250 [============================>.] - ETA: 0s - loss: 0.2594 - accuracy: 0.8875WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2585 - accuracy: 0.8879
Epoch 44/100
246/250 [============================>.] - ETA: 0s - loss: 0.2606 - accuracy: 0.8868WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2620 - accuracy: 0.8865
Epoch 45/100
234/250 [===========================>..] - ETA: 0s - loss: 0.2572 - accuracy: 0.8869WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2580 - accuracy: 0.8857
Epoch 46/100
246/250 [============================>.] - ETA: 0s - loss: 0.2552 - accuracy: 0.8858WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2556 - accuracy: 0.8854
Epoch 47/100
236/250 [===========================>..] - ETA: 0s - loss: 0.2550 - accuracy: 0.8855WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2543 - accuracy: 0.8865
Epoch 48/100
246/250 [============================>.] - ETA: 0s - loss: 0.2526 - accuracy: 0.8885WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2527 - accuracy: 0.8884
Epoch 49/100
249/250 [============================>.] - ETA: 0s - loss: 0.2568 - accuracy: 0.8878WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2573 - accuracy: 0.8875
Epoch 50/100
246/250 [============================>.] - ETA: 0s - loss: 0.2511 - accuracy: 0.8896WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 3ms/step - loss: 0.2516 - accuracy: 0.8891
Epoch 51/100
249/250 [============================>.] - ETA: 0s - loss: 0.2492 - accuracy: 0.8907WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2491 - accuracy: 0.8907
Epoch 52/100
231/250 [==========================>...] - ETA: 0s - loss: 0.2499 - accuracy: 0.8874WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2485 - accuracy: 0.8881
Epoch 53/100
232/250 [==========================>...] - ETA: 0s - loss: 0.2524 - accuracy: 0.8905WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 3ms/step - loss: 0.2509 - accuracy: 0.8907
Epoch 54/100
248/250 [============================>.] - ETA: 0s - loss: 0.2448 - accuracy: 0.8940WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2451 - accuracy: 0.8941
Epoch 55/100
243/250 [============================>.] - ETA: 0s - loss: 0.2410 - accuracy: 0.8934WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2428 - accuracy: 0.8934
Epoch 56/100
231/250 [==========================>...] - ETA: 0s - loss: 0.2421 - accuracy: 0.8908WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2447 - accuracy: 0.8910
Epoch 57/100
249/250 [============================>.] - ETA: 0s - loss: 0.2480 - accuracy: 0.8919WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2485 - accuracy: 0.8917
Epoch 58/100
247/250 [============================>.] - ETA: 0s - loss: 0.2460 - accuracy: 0.8920WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2463 - accuracy: 0.8915
Epoch 59/100
248/250 [============================>.] - ETA: 0s - loss: 0.2366 - accuracy: 0.8949WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2369 - accuracy: 0.8945
Epoch 60/100
240/250 [===========================>..] - ETA: 0s - loss: 0.2365 - accuracy: 0.8932WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2359 - accuracy: 0.8934
Epoch 61/100
247/250 [============================>.] - ETA: 0s - loss: 0.2395 - accuracy: 0.8935WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2399 - accuracy: 0.8935
Epoch 62/100
241/250 [===========================>..] - ETA: 0s - loss: 0.2398 - accuracy: 0.8930WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2388 - accuracy: 0.8930
Epoch 63/100
234/250 [===========================>..] - ETA: 0s - loss: 0.2359 - accuracy: 0.8946WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy
250/250 [==============================] - 1s 2ms/step - loss: 0.2343 - accuracy: 0.8951
Epoch 64/100
231/250 [==========================>...] - ETA: 0s - loss: 0.2368 - accuracy: 0.8948WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,accuracy

In [28]:
model.save('model.h5')

In [29]:
# load tensorboard 
%load_ext tensorboard

In [ ]:
%tensorboard --logdir logs/fit